// src/utils/services.js

export const layananMap = [
  { code: 'A', produk: 'Refleksi', durasi: 60 },
  { code: 'B', produk: 'Refleksi', durasi: 90 },
  { code: 'C', produk: 'Refleksi', durasi: 120 },
  { code: '1', produk: 'Javanese Massage', durasi: 60 },
  { code: '1A', produk: 'Javanese Massage', durasi: 90 },
  { code: '1B', produk: 'Javanese Massage', durasi: 120 },
  { code: '2A', produk: 'Swedish Massage', durasi: 90 },
  { code: '2B', produk: 'Swedish Massage', durasi: 120 },
  { code: '3', produk: 'Lulur / Scrubbing', durasi: 60 },
  { code: '4A', produk: 'Shiatsu', durasi: 90 },
  { code: '4B', produk: 'Shiatsu', durasi: 120 },
  { code: '5', produk: 'Manicure', durasi: 60 },
  { code: '6', produk: 'Pedicure', durasi: 60 },
  { code: '7', produk: 'Dry Back Massage', durasi: 60 },
  { code: '7A', produk: 'Dry Back Massage', durasi: 90 },
  { code: '8', produk: 'Totok Wajah', durasi: 60 },
  { code: 'RM1', produk: 'Refleksi + Massage', durasi: 90 },
  { code: 'RM2', produk: 'Refleksi + Massage', durasi: 120 },
  { code: 'MT1', produk: 'Massage + Totok Wajah', durasi: 90 },
  { code: 'MT2', produk: 'Massage + Totok Wajah', durasi: 120 }
];

export const layananRumahSpa = [
  { code: '1', produk: 'Refleksi', durasi: 60 },
  { code: '2', produk: 'Refleksi', durasi: 90 },
  { code: '3', produk: 'Refleksi', durasi: 120 },
  { code: '2m', produk: 'Refleksi + Massage', durasi: 90 },
  { code: '3m', produk: 'Refleksi + Massage', durasi: 120 },
  { code: '4', produk: 'Javanese Massage', durasi: 60 },
  { code: '5', produk: 'Javanese Massage', durasi: 90 },
  { code: '6', produk: 'Javanese Massage', durasi: 120 },
  { code: '7', produk: 'Swedish Massage', durasi: 60 },
  { code: '8', produk: 'Swedish Massage', durasi: 90 },
  { code: '9', produk: 'Swedish Massage', durasi: 120 },
  { code: '10', produk: 'Japanese Massage / Shiatsu', durasi: 60 },
  { code: '11', produk: 'Japanese Massage / Shiatsu', durasi: 90 },
  { code: '12', produk: 'Japanese Massage / Shiatsu', durasi: 120 },
  { code: '13', produk: 'Thai Massage', durasi: 60 },
  { code: '14', produk: 'Thai Massage', durasi: 90 },
  { code: '15', produk: 'Thai Massage', durasi: 120 },
  { code: '16', produk: 'Balinese Massage', durasi: 60 },
  { code: '17', produk: 'Balinese Massage', durasi: 90 },
  { code: '18', produk: 'Balinese Massage', durasi: 120 },
  { code: '19', produk: 'COM. MSG (Java + Thai)', durasi: 60 },
  { code: '20', produk: 'COM. MSG (Java + Thai)', durasi: 90 },
  { code: '21', produk: 'COM. MSG (Java + Thai)', durasi: 120 },
  { code: '22', produk: 'COM. MSG (Java + Japan)', durasi: 60 },
  { code: '23', produk: 'COM. MSG (Java + Japan)', durasi: 90 },
  { code: '24', produk: 'COM. MSG (Java + Japan)', durasi: 120 },
  { code: '25', produk: 'Hot Stone Massage', durasi: 60 },
  { code: '26', produk: 'Hot Stone Massage', durasi: 90 },
  { code: '27', produk: 'Hot Stone Massage', durasi: 120 },
  { code: '28', produk: 'V. Spa', durasi: 60 },
  { code: '29', produk: 'Breast Care', durasi: 60 },
  { code: '30', produk: 'Scrubbing (Lulur)', durasi: 60 },
  { code: '31', produk: 'Standard Spa', durasi: 120 },
  { code: '32', produk: 'Warm Ball Spa', durasi: 120 },
  { code: '33', produk: 'Javanese Herbal Spa', durasi: 150 },
  { code: '34', produk: 'Avocado Spa', durasi: 150 },
  { code: '35', produk: 'Green Tea Spa', durasi: 150 },
  { code: '36', produk: 'Coffee Mud Spa', durasi: 150 },
  { code: '37', produk: 'Lavender Spa', durasi: 150 },
  { code: '38', produk: 'Relaxing Spa', durasi: 150 },
  { code: '39', produk: 'Chocolate Spa', durasi: 180 },
  { code: '40', produk: 'Kendedes Spa', durasi: 180 },
  { code: '41', produk: 'Whitening Spa', durasi: 180 },
  { code: '42', produk: 'Bengkoang Spa', durasi: 180 },
  { code: '43', produk: 'Jasmine Spa', durasi: 180 },
  { code: '44', produk: 'Harmony Sensation Spa', durasi: 180 },
  { code: '45', produk: 'Putri Pinang Masak (Javanese Spa)', durasi: 0, note: 'PRWT Ke 1' },
  { code: '46', produk: 'Putri Pinang Masak (Kendedes Spa)', durasi: 0, note: 'PRWT Ke 2' },
  { code: '47', produk: 'Putri Rambut Selako (Javanese Spa)', durasi: 0, note: 'PRWT Ke 1' },
  { code: '48', produk: 'Putri Rambut Selako (Whitening Spa)', durasi: 0, note: 'PRWT Ke 2' },
  { code: '49', produk: 'Putri Rambut Selako (Kendedes Spa)', durasi: 0, note: 'PRWT Ke 3' },
  { code: '50', produk: 'Putri Dayang Merindu (Javanese Spa)', durasi: 0, note: 'PRWT Ke 1' },
  { code: '51', produk: 'Putri Dayang Merindu (Bengkoang Spa)', durasi: 0, note: 'PRWT Ke 2' },
  { code: '52', produk: 'Putri Dayang Merindu (Kendedes Spa)', durasi: 0, note: 'PRWT Ke 3' },
  { code: '53', produk: 'Putri Kembang Dadar (Javanese Spa)', durasi: 0, note: 'PRWT Ke 1' },
  { code: '54', produk: 'Putri Kembang Dadar (Whitening Spa)', durasi: 0, note: 'PRWT Ke 2' },
  { code: '55', produk: 'Putri Kembang Dadar (Bengkoang Spa)', durasi: 0, note: 'PRWT Ke 3' },
  { code: '56', produk: 'Putri Kembang Dadar (Kendedes Spa)', durasi: 0, note: 'PRWT Ke 4' },
  { code: '57', produk: 'Totok Wajah', durasi: 60 },
  { code: '58', produk: 'Masker Badan', durasi: 60 },
  { code: '60', produk: 'Massage + Totok Wajah', durasi: 90 },
  { code: '61', produk: 'Massage + Totok Wajah', durasi: 120 },
];

export const kategoriMap = {
  'R': 'Request',
  'U': 'Urutan',
  'PN': 'Permintaan Nama'
};
